---
version: "3"
services:
 devopsdb:
   image: shaikmustafa/docker:dbimg
   ports:
     - "3306:3306"

 application:
   image: shaikmustafa/docker:appimg
   ports:
     - "1111-1113:8080"
   deploy:
      replicas: 3
   depends_on:
     - "devopsdb"
