---
version: "3"
services:
 devopsdb:
   image: navyakoneti/docker:dbimage
   ports:
     - "3306:3306"
   networks:
     - appnetwork
     - dbnetwork
   volumes:
     - appvolume:/usr/share/nginx/html/

 application:
   image: navyakoneti/docker:appimage
   ports:
     - "1111-1113:8080"
   deploy:
      replicas: 3
   depends_on:
     - "devopsdb"
   networks:
     - appnetwork
     - dbnetwork
   volumes:
     - dbvolume:/usr/local/apache2/htdocs/
networks:
  appnetwork:
  dbnetwork:
volumes:
  appvolume:
  dbvolume:
