---
version: "3"
services:
 devopsdb:
   image: navyakoneti/docker:dbimage
   ports:
     - "3306:3306"

 application:
   image: navyakoneti/docker:appimage
   ports:
     - "1111-1113:8080"
   deploy:
      replicas: 3
   depends_on:
     - "devopsdb"
